import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    brand: "KarnaliKrishna",
    home: "Home",
    cart: "Cart",
    support: "Support",
    profile: "Profile",
    login: "Login",
    register: "Register",
    logout: "Logout",
    dashboard: "Dashboard",
    searchPlaceholder: "Search products...",
    category: "Category",
    allCategories: "All Categories",
    branch: "Branch",
    allBranches: "All Branches",
    price: "Price",
    salePrice: "Sale Price",
    originalPrice: "Original Price",
    stock: "Stock",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    featuredProducts: "Featured Products",
    reviews: "Reviews",
    specifications: "Specifications",
    ratings: "Ratings",
    totalSales: "Total Sales",
    totalOrders: "Total Orders",
    totalCustomers: "Total Customers",
    totalProducts: "Total Products",
    totalBranches: "Total Branches",
    totalCoupons: "Total Coupons",
    totalIssues: "Total Issues",
    orderStatus: "Order Status",
    pending: "Pending",
    confirmed: "Confirmed",
    processing: "Processing",
    shipped: "Shipped",
    delivered: "Delivered",
    cancelled: "Cancelled",
    checkout: "Checkout",
    shippingAddress: "Shipping Address",
    paymentMethod: "Payment Method",
    cod: "Cash on Delivery",
    esewa: "eSewa Wallet",
    khalti: "Khalti Wallet",
    fonepay: "Fonepay",
    placeOrder: "Place Order",
    coupon: "Coupon",
    apply: "Apply",
    subtotal: "Subtotal",
    discount: "Discount",
    shipping: "Shipping",
    vat: "VAT (13%)",
    total: "Total",
    whatsappSupport: "WhatsApp Support",
    branchHead: "Branch Head",
    customerSupport: "Customer Support",
    pendingApproval: "Pending Approval",
    approve: "Approve",
    reject: "Reject",
    exportPdf: "Export PDF",
    exportExcel: "Export Excel",
    language: "Language",
    theme: "Theme",
    settings: "Settings",
    coupons: "Coupons",
    addressBook: "Address Book",
    addNewAddress: "Add New Address",
    gpsLocation: "Live GPS Location",
    pinLocation: "Pin location on map",
    fullName: "Full Name",
    email: "Email Address",
    phone: "Phone Number",
    password: "Password",
    profilePhoto: "Profile Photo",
    issueReport: "Customer Issue Report",
    issueCategory: "Issue Category",
    description: "Description",
    resolution: "Resolution Details",
    status: "Status",
    open: "Open",
    inProgress: "In Progress",
    resolved: "Resolved",
    action: "Actions",
    noProducts: "No products found.",
    welcomeBack: "Welcome back!",
    orderTimeline: "Order Timeline",
    orderInvoice: "Download PDF Invoice",
  },
  ne: {
    brand: "कर्णाली कृष्ण",
    home: "गृह पृष्ठ",
    cart: "झोला (कार्ट)",
    support: "सहायता",
    profile: "प्रोफाइल",
    login: "लगइन",
    register: "दर्ता गर्नुहोस्",
    logout: "लगआउट",
    dashboard: "डैशबोर्ड",
    searchPlaceholder: "सामानहरू खोज्नुहोस्...",
    category: "वर्ग (Category)",
    allCategories: "सबै वर्गहरू",
    branch: "शाखा",
    allBranches: "सबै शाखाहरू",
    price: "मूल्य",
    salePrice: "बिक्री मूल्य",
    originalPrice: "वास्तविक मूल्य",
    stock: "स्टक (मौजदात)",
    addToCart: "झोलामा थप्नुहोस्",
    buyNow: "तुरुन्त किन्नुहोस्",
    featuredProducts: "विशेष उत्पादनहरू",
    reviews: "प्रतिक्रियाहरू",
    specifications: "विशिष्टताहरू",
    ratings: "मूल्याङ्कन",
    totalSales: "कुल बिक्री",
    totalOrders: "कुल अर्डरहरू",
    totalCustomers: "कुल ग्राहकहरू",
    totalProducts: "कुल उत्पादनहरू",
    totalBranches: "कुल शाखाहरू",
    totalCoupons: "कुल कुपनहरू",
    totalIssues: "कुल समस्याहरू",
    orderStatus: "अर्डरको स्थिति",
    pending: "पेन्डिङ (बाँकी)",
    confirmed: "स्वीकृत",
    processing: "प्रक्रियामा",
    shipped: "ढुवानीमा",
    delivered: "डेलिभर भएको",
    cancelled: "रद्द भएको",
    checkout: "चेकआउट",
    shippingAddress: "डेलिभरी ठेगाना",
    paymentMethod: "भुक्तानी तरिका",
    cod: "डेलिभरीमा नगद (COD)",
    esewa: "ईसेवा (eSewa)",
    khalti: "खल्ती (Khalti)",
    fonepay: "फोनपे (Fonepay)",
    placeOrder: "अर्डर गर्नुहोस्",
    coupon: "कुपन",
    apply: "लागु गर्नुहोस्",
    subtotal: "उप-योग",
    discount: "छुट",
    shipping: "डेलिभरी शुल्क",
    vat: "भ्याट (१३%)",
    total: "कुल जम्मा",
    whatsappSupport: "व्हाट्सएप सहायता",
    branchHead: "शाखा प्रमुख",
    customerSupport: "ग्राहक सेवा",
    pendingApproval: "स्वीकृतिको पर्खाइमा",
    approve: "स्वीकृत गर्नुहोस्",
    reject: "अस्वीकृत गर्नुहोस्",
    exportPdf: "PDF डाउनलोड",
    exportExcel: "Excel डाउनलोड",
    language: "भाषा",
    theme: "थिम",
    settings: "सेटिङहरू",
    coupons: "कुपनहरू",
    addressBook: "ठेगाना पुस्तिका",
    addNewAddress: "नयाँ ठेगाना थप्नुहोस्",
    gpsLocation: "लाइभ GPS स्थान",
    pinLocation: "नक्सामा स्थान छान्नुहोस्",
    fullName: "पूरा नाम",
    email: "इमेल ठेगाना",
    phone: "फोन नम्बर",
    password: "पासवर्ड",
    profilePhoto: "प्रोफाइल फोटो",
    issueReport: "ग्राहक समस्या रिपोर्ट",
    issueCategory: "समस्याको विधा",
    description: "विवरण",
    resolution: "समाधान विवरण",
    status: "स्थिति",
    open: "खुला",
    inProgress: "प्रक्रियामा",
    resolved: "समाधान भएको",
    action: "कार्यहरू",
    noProducts: "कुनै उत्पादनहरू फेला परेनन्।",
    welcomeBack: "स्वागत छ!",
    orderTimeline: "अर्डरको टाइमलाइन",
    orderInvoice: "PDF बिल डाउनलोड",
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang][key] || key;
  };

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'en' ? 'ne' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
